version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Node version 12 installed"
      - echo "Installing source NPM dependencies..."
      - npm install

  build:
    commands:
      - echo "Building React app"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
