version: 0.2
env:
  variables:
    REACT_APP_API_URL: postgres://test:password@localhost:5432/ndi
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Node version 12 installed

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  build:
    commands:
      - echo Building React app
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
