version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version $(node -v) installed"
      - echo "Installing source NPM dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building React app"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
